# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
filter = {
  except_tables = [
    "project_activities",
  ]
}
# filter = { only_tables = ["blogs", "users", "organizations", "users_organizations"] }
